param(
    [Parameter(Position = 0)]
    [ValidateSet('major', 'minor', 'patch', 'prerelease')]
    [string]$Bump = 'patch',

    [Parameter()]
    [string]$PreReleaseLabel = 'beta',

    [Parameter()]
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'

function Get-LatestTag {
    $tag = git tag --list 'v*' --sort=-version:refname | Select-Object -First 1
    if (-not $tag) {
        return 'v0.0.0'
    }
    return $tag
}

function Parse-Version([string]$Tag) {
    $base = $Tag.TrimStart('v')
    $parts = $base -split '-', 2
    $semver = $parts[0] -split '\.'
    $pre = if ($parts.Count -gt 1) { $parts[1] } else { $null }
    return @{
        Major   = [int]$semver[0]
        Minor   = [int]$semver[1]
        Patch   = [int]$semver[2]
        Pre     = $pre
    }
}

function Bump-Version($ver, [string]$Bump, [string]$PreReleaseLabel) {
    switch ($Bump) {
        'major' {
            $ver.Major++
            $ver.Minor = 0
            $ver.Patch = 0
            $ver.Pre = $null
        }
        'minor' {
            $ver.Minor++
            $ver.Patch = 0
            $ver.Pre = $null
        }
        'patch' {
            $ver.Patch++
            $ver.Pre = $null
        }
        'prerelease' {
            if ($ver.Pre) {
                $parts = $ver.Pre -split '\.'
                if ($parts.Count -eq 2 -and $parts[1] -as [int]) {
                    $parts[1] = [int]$parts[1] + 1
                } else {
                    $parts = @($PreReleaseLabel, '1')
                }
                $ver.Pre = $parts -join '.'
            } else {
                $ver.Patch++
                $ver.Pre = "$PreReleaseLabel.1"
            }
        }
    }

    $versionStr = "$($ver.Major).$($ver.Minor).$($ver.Patch)"
    if ($ver.Pre) {
        $versionStr += "-$($ver.Pre)"
    }
    return "v$versionStr"
}

$latestTag = Get-LatestTag
$ver = Parse-Version $latestTag
$newTag = Bump-Version $ver $Bump $PreReleaseLabel

Write-Host "Current tag: $latestTag"
Write-Host "New tag:     $newTag"
Write-Host "Release notes will be auto-generated by the workflow."

if ($DryRun) {
    Write-Host "`n[Dry-run] No changes made."
    return
}

$confirmation = Read-Host "`nCreate and push tag '$newTag'? (y/N)"
if ($confirmation -ne 'y') {
    Write-Host "Aborted."
    exit 1
}

git tag $newTag
git push origin $newTag

Write-Host "`nTag $newTag pushed. Release workflow triggered:"
Write-Host "https://github.com/clystian/DotnetFormatExtensions/actions"
